<?php

namespace ContainerQ6FgKKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAjaxControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AjaxController' shared autowired service.
     *
     * @return \App\Controller\AjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AjaxController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/BinanceAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/BittrexAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/CoinbaseAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/GateAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/HuobiAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/KrakenAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/KuCoinAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/MEXCAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/DebankAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/MergeCryptos.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Utilities.php';

        $container->services['App\\Controller\\AjaxController'] = $instance = new \App\Controller\AjaxController(new \App\Services\Cryptos\BinanceAPI(), new \App\Services\Cryptos\BittrexAPI(), new \App\Services\Cryptos\CoinbaseAPI(), new \App\Services\Cryptos\GateAPI(), new \App\Services\Cryptos\HuobiAPI(), new \App\Services\Cryptos\KrakenAPI(), new \App\Services\Cryptos\KuCoinAPI(), new \App\Services\Cryptos\MEXCAPI(), new \App\Services\Cryptos\DebankAPI(), ($container->privates['App\\Services\\Cryptos\\SubscanAPI'] ?? $container->load('getSubscanAPIService')), ($container->services['App\\Services\\Cryptos\\CoinGeckoAPI'] ?? $container->load('getCoinGeckoAPIService')), new \App\Services\Cryptos\MergeCryptos(), ($container->services['App\\Services\\Cryptos\\ChartJS'] ?? $container->load('getChartJSService')), ($container->privates['App\\Services\\Utilities'] ?? ($container->privates['App\\Services\\Utilities'] = new \App\Services\Utilities())));

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Controller\\AjaxController', $container));

        return $instance;
    }
}
