<?php

namespace ContainerQ6FgKKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoinGeckoAPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Services\Cryptos\CoinGeckoAPI' shared autowired service.
     *
     * @return \App\Services\Cryptos\CoinGeckoAPI
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/CoinGeckoAPI.php';

        $container->services['App\\Services\\Cryptos\\CoinGeckoAPI'] = $instance = new \App\Services\Cryptos\CoinGeckoAPI();

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Services\\Cryptos\\CoinGeckoAPI', $container));

        return $instance;
    }
}
