<?php

namespace ContainerQ6FgKKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatformTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PlatformType' shared autowired service.
     *
     * @return \App\Form\PlatformType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PlatformType.php';

        return $container->privates['App\\Form\\PlatformType'] = new \App\Form\PlatformType();
    }
}
