<?php

namespace ContainerQ6FgKKm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscanAPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Cryptos\SubscanAPI' shared autowired service.
     *
     * @return \App\Services\Cryptos\SubscanAPI
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/SubscanAPI.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Utilities.php';

        return $container->privates['App\\Services\\Cryptos\\SubscanAPI'] = new \App\Services\Cryptos\SubscanAPI(($container->privates['App\\Services\\Utilities'] ?? ($container->privates['App\\Services\\Utilities'] = new \App\Services\Utilities())));
    }
}
