<?php

namespace ContainerZx51FHx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChartJSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Services\Cryptos\ChartJS' shared autowired service.
     *
     * @return \App\Services\Cryptos\ChartJS
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Cryptos/ChartJS.php';

        $container->services['App\\Services\\Cryptos\\ChartJS'] = $instance = new \App\Services\Cryptos\ChartJS();

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Services\\Cryptos\\ChartJS', $container));

        return $instance;
    }
}
