<?php

namespace ContainerZx51FHx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanelControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PanelController' shared autowired service.
     *
     * @return \App\Controller\PanelController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PanelController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Utilities.php';

        $container->services['App\\Controller\\PanelController'] = $instance = new \App\Controller\PanelController(($container->privates['App\\Services\\Utilities'] ?? ($container->privates['App\\Services\\Utilities'] = new \App\Services\Utilities())));

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Controller\\PanelController', $container));

        return $instance;
    }
}
