<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ6FgKKm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ6FgKKm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ6FgKKm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ6FgKKm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ6FgKKm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q6FgKKm',
    'container.build_id' => '11795590',
    'container.build_time' => 1649403309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ6FgKKm');
