<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.c3e9a731.js',
                '/build/755.5a8586e9.js',
                '/build/582.270073a0.js',
                '/build/455.7ec4efb9.js',
                '/build/app.1ce9a275.js',
            ],
            'css' => [
                '/build/455.069aa3e8.css',
                '/build/app.55b80b5b.css',
            ],
        ],
        'cryptos' => [
            'js' => [
                '/build/runtime.c3e9a731.js',
                '/build/755.5a8586e9.js',
                '/build/cryptos.9c9c980c.js',
            ],
        ],
        'polkadot' => [
            'js' => [
                '/build/runtime.c3e9a731.js',
                '/build/582.270073a0.js',
                '/build/987.e70f6c20.js',
                '/build/polkadot.52d53f76.js',
            ],
        ],
    ],
],

]];
